# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60fe3b2dbc7b6a8ee3c964d1231894bea01ecbd078e9e1caed85efd4013e74bddfcbe309319108a86c6dcbf18fdd42a50ecb174af95533fdbd90dc512725b8bc

test:
  secret_key_base: 1b67195dd4e7cb5317c96aa59f0d2c0556941b79131d80082afd75e0fffc91c5af87c68bb6000e364dd76e10716de1cc75ec413062d16eaf986deb33b83386aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
